language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- yarn install
before_script: 
script:
- yarn build
after_script:
- cd ./dist

branches:
  only:
  - master
notifications:
  slack:
    rooms:
      #- totorocorp:k4RhBu6TpTLBdQ1hPTKMSglB#web-notification
      - secure: "111111UqVggaEO1cXVdbsGwWct25KVS3f9cf6nniFdAYEbUkN8gaIcNCnEXSA6XTNZc2Fqz30oR2OPZAlwNh7LpGJN/b9RqFd5V/eNF9D/Lug6oiE29w0dObDv2HHXkDGVOGtdR9jn1mimceytP/Am92LyV56BMdieMlL8FU3YdhwKAetnOOEGUrMnyOojhKYxNucKmfaCgURxKJo091JAjrAa5CMO6BpDIIZGBzwztMlGOyyLNLOm0tuus2f3A9QhJ6KzfSIuG5RotaxWNMG5TVEnkQ0Mfl9o8l6kspZ+Lzvgeo/lJtdiKtxxTXNEJEJ6nzm+4k8jM8uSR4A5TslHt/TDVJes8OUHfY3bzW36R+XUoubuOAZSkdEbonZVrFej5ynW902ljvRigtdoHJ5w76Zav9DYgZ6o23MedVw3efFz1V4fl01Nj9sLnEXelVDPrsbZfyXXXKQ1rEaXsK0qxwiEQsYmJHcxTeQekX0D8k4x/UEXquaI+Ol0QMY+ifmR3WBXnO+e8aOHccZrdV58vrt7L7Acg1oEBYRk4fYUr0BkUz16VrQGikNhOTtaONLXVpNFMZmM6WL4qJPl5hFqUk3XJrZSDfSpjqJToLErNUZ/wBK6C6cvwMsULtRtXvWDqtgt92PeaCNgmFHb2Jy1LkD/ybGPBxXIKbsHNNUhspBHDFA="
    on_success: always
    on_failure: always
    template:
    - Repo `%{repository_slug}`build (<%{build_url}|#%{build_number}>) for commit
      (<%{compare_url}|%{commit}>) on branch `%{branch}` by `%{author}`.
    - 'Execution time: *%{duration}*'
    - 'Message: %{message}'
